typography_spectrum: 0.47392105241306126
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9285776717588305
  lightness: 0.9576753727160394
  saturation: 0.8015428769867867
  rhythmicContrast: 0.6051677905488759
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7796001615934074
analytics:
  google: null
  facebook: null
  twitter: null
name: Altura Libre Music
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Timeless Music
purpose: []
